package com.esgis2026.assigame.entities;

import jakarta.persistence.*;
import lombok.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a product category on the Assigame platform.
 * <p>
 * Categories are used to organize and classify products for easier browsing.
 * Examples: Jeux Vidéo, Consoles, Accessoires, etc.
 * </p>
 * 
 * @author Assigame Team
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "categorie_produit")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CategorieProduit {

    /**
     * Unique identifier for the category.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_categorie")
    private Long idCategorie;

    /**
     * Name of the category.
     * Maximum length: 100 characters.
     */
    @Column(name = "nom_categorie", nullable = false, length = 100)
    private String nomCategorie;

    /**
     * Description of the category.
     * Stored as TEXT to allow long descriptions.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * List of products belonging to this category.
     * Cascade operations: ALL (create, update, delete).
     * Orphan removal enabled.
     */
    @OneToMany(mappedBy = "categorieProduit", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Produit> produits = new ArrayList<>();

    /**
     * Returns a string representation of the category.
     * 
     * @return String containing category details
     */
    @Override
    public String toString() {
        return "CategorieProduit [idCategorie=" + idCategorie + ", nomCategorie=" + nomCategorie + ", description="
                + description + ", produits=" + produits + "]";
    }
}
