package com.esgis2026.assigame.entities;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity representing a conversation between a buyer and a seller about a specific product.
 * <p>
 * Conversations are created when a buyer first contacts a seller about a product.
 * Each conversation is unique per buyer-seller-product triplet.
 * </p>
 * 
 * @author Assigame Team
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "conversation", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"buyer_id", "id_utilisateur", "id_produit"})
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Conversation {

    /**
     * Unique identifier for the conversation.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_conversation")
    private Long idConversation;

    /**
     * Identifier of the buyer.
     * Can be a guest ID (for unauthenticated users) or a user ID.
     * Maximum length: 150 characters.
     */
    @Column(name = "buyer_id", nullable = false, length = 150)
    private String buyerId;

    /**
     * The seller (registered user) participating in the conversation.
     * Lazy loading for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_utilisateur", nullable = false)
    private Utilisateur seller;

    /**
     * The product that is the subject of this conversation.
     * Lazy loading for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_produit", nullable = false)
    private Produit product;

    /**
     * Date and time when the conversation was created.
     * Automatically set on creation and cannot be updated.
     */
    @Column(name = "date_creation", nullable = false, updatable = false)
    private LocalDateTime dateCreation;

    /**
     * Lifecycle callback that sets the creation date before persisting.
     * Automatically called by JPA before the entity is saved to the database.
     */
    @PrePersist
    protected void onCreate() {
        this.dateCreation = LocalDateTime.now();
    }
}
