package com.esgis2026.assigame.entities;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity representing a message exchanged within a conversation.
 * <p>
 * Messages are sent by either the buyer or the seller and are stored
 * with their content, sender information, and timestamp.
 * </p>
 * 
 * @author Assigame Team
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "message")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Message {

    /**
     * Unique identifier for the message.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_message")
    private Long idMessage;

    /**
     * The conversation this message belongs to.
     * Lazy loading for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_conversation", nullable = false)
    private Conversation conversation;

    /**
     * The type of sender (BUYER or SELLER).
     * Stored as enum string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "sender_type", nullable = false, length = 20)
    private SenderType senderType;

    /**
     * Identifier of the sender.
     * Can be a guest ID (for unauthenticated buyers) or a user ID.
     * Maximum length: 150 characters.
     */
    @Column(name = "sender_id", nullable = false, length = 150)
    private String senderId;

    /**
     * Content of the message.
     * Stored as TEXT to allow long messages.
     */
    @Column(name = "contenu", nullable = false, columnDefinition = "TEXT")
    private String contenu;

    /**
     * Date and time when the message was sent.
     * Automatically set on creation and cannot be updated.
     */
    @Column(name = "date_envoi", nullable = false, updatable = false)
    private LocalDateTime dateEnvoi;

    /**
     * Lifecycle callback that sets the send date before persisting.
     * Automatically called by JPA before the entity is saved to the database.
     */
    @PrePersist
    protected void onCreate() {
        this.dateEnvoi = LocalDateTime.now();
    }
}
