package com.esgis2026.assigame.entities;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;

/**
 * Entity representing a product listed for sale on the Assigame platform.
 * <p>
 * Products are published by users (sellers) and can be browsed by visitors.
 * Each product has a name, description, price, image, status, and belongs to a category.
 * </p>
 * 
 * @author Assigame Team
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "produit")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Produit {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_produit")
    private Long idProduit;

    /**
     * Name of the product.
     * Maximum length: 150 characters.
     */
    @Column(name = "nom_produit", nullable = false, length = 150)
    private String nomProduit;

    /**
     * Detailed description of the product.
     * Stored as TEXT to allow long descriptions.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Price of the product in FCFA (CFA Franc).
     * Precision: 10 digits, scale: 2 decimal places.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal prix;

    /**
     * Image of the product stored as binary data (BLOB).
     * Typically a base64-encoded image.
     */
    @Lob
    @Column(name = "image")
    private byte[] image;

    /**
     * Date and time when the product was added to the platform.
     * Automatically set on creation.
     */
    @Column(name = "date_ajout", nullable = false)
    private LocalDateTime dateAjout;

    /**
     * Current status of the product.
     * Possible values: DISPONIBLE, RÉSERVÉ, VENDU.
     * Maximum length: 50 characters.
     */
    @Column(length = 50)
    private String statut;

    /**
     * The user (seller) who published this product.
     * Lazy loading for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_utilisateur", nullable = false)
    private Utilisateur utilisateur;

    /**
     * The category this product belongs to.
     * Lazy loading for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_categorie", nullable = false)
    private CategorieProduit categorieProduit;

    /**
     * Lifecycle callback that sets the addition date before persisting.
     * Automatically called by JPA before the entity is saved to the database.
     */
    @PrePersist
    protected void onCreate() {
        this.dateAjout = LocalDateTime.now();
    }

    /**
     * Returns a string representation of the product.
     * 
     * @return String containing product details
     */
    @Override
    public String toString() {
        return "Produit [idProduit=" + idProduit + ", nomProduit=" + nomProduit + ", description=" + description
                + ", prix=" + prix + ", image=" + Arrays.toString(image) + ", dateAjout=" + dateAjout + ", statut="
                + statut + ", utilisateur=" + utilisateur + ", categorieProduit=" + categorieProduit + "]";
    }
}
