package com.esgis2026.assigame.entities;

import jakarta.persistence.*;
import lombok.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a user type/role on the Assigame platform.
 * <p>
 * User types determine the permissions and access level of users.
 * Common types: VENDEUR (Seller), ADMIN (Administrator).
 * </p>
 * 
 * @author Assigame Team
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "type_utilisateur")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TypeUtilisateur {

    /**
     * Unique identifier for the user type.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_type_utilisateur")
    private Long idTypeUtilisateur;

    /**
     * Label/name of the user type.
     * Examples: "VENDEUR", "ADMIN".
     * Maximum length: 100 characters.
     */
    @Column(nullable = false, length = 100)
    private String libelle;

    /**
     * Description of the user type.
     * Stored as TEXT to allow long descriptions.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * List of users having this user type.
     * Cascade operations: ALL (create, update, delete).
     * Orphan removal enabled.
     */
    @OneToMany(mappedBy = "typeUtilisateur", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Utilisateur> utilisateurs = new ArrayList<>();

    /**
     * Returns a string representation of the user type.
     * 
     * @return String containing user type details
     */
    @Override
    public String toString() {
        return "TypeUtilisateur [idTypeUtilisateur=" + idTypeUtilisateur + ", libelle=" + libelle + ", description="
                + description + ", utilisateurs=" + utilisateurs + "]";
    }
}
