package com.esgis2026.assigame.entities;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a user in the Assigame platform.
 * <p>
 * Users can be sellers or administrators and can publish products for sale.
 * Each user has a unique login and email, and is associated with a user type (role).
 * </p>
 * 
 * @author Assigame Team
 * @version 1.0
 * @since 2026
 */
@Entity
@Table(name = "utilisateur")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Utilisateur {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_utilisateur")
    private Long idUtilisateur;

    /**
     * Last name of the user.
     * Maximum length: 100 characters.
     */
    @Column(nullable = false, length = 100)
    private String nom;

    /**
     * First name of the user.
     * Maximum length: 100 characters.
     */
    @Column(nullable = false, length = 100)
    private String prenom;

    /**
     * Email address of the user.
     * Must be unique across all users.
     * Maximum length: 150 characters.
     */
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /**
     * Login identifier for authentication.
     * Must be unique across all users.
     * Maximum length: 50 characters.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String login;

    /**
     * Password hash for authentication.
     * Stored as a BCrypt hash, not plain text.
     */
    @Column(name = "mot_de_passe", nullable = false)
    private String motDePasse;

    /**
     * Phone number of the user.
     * Optional field.
     * Maximum length: 20 characters.
     */
    @Column(length = 20)
    private String telephone;

    /**
     * Physical address of the user.
     * Optional field.
     */
    private String adresse;

    /**
     * Date and time when the user account was created.
     * Automatically set on creation and cannot be updated.
     */
    @Column(name = "date_inscription", nullable = false, updatable = false)
    private LocalDateTime dateInscription;

    /**
     * Flag indicating whether the user account is active.
     * Default value: true.
     * Inactive users cannot log in or perform actions.
     */
    @Column(nullable = false)
    private boolean actif = true;

    /**
     * The type/role of the user (e.g., VENDEUR, ADMIN).
     * This determines the user's permissions and access level.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_type_utilisateur", nullable = false)
    private TypeUtilisateur typeUtilisateur;

    /**
     * List of products published by this user.
     * Cascade operations: ALL (create, update, delete).
     * Orphan removal enabled.
     */
    @OneToMany(mappedBy = "utilisateur", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Produit> produits = new ArrayList<>();

    /**
     * Lifecycle callback that sets the registration date before persisting.
     * Automatically called by JPA before the entity is saved to the database.
     */
    @PrePersist
    protected void onCreate() {
        this.dateInscription = LocalDateTime.now();
    }

    /**
     * Returns a string representation of the user.
     * 
     * @return String containing user details (excluding password for security)
     */
    @Override
    public String toString() {
        return "Utilisateur [idUtilisateur=" + idUtilisateur + ", nom=" + nom + ", prenom=" + prenom + ", email="
                + email + ", login=" + login + ", motDePasse=" + motDePasse + ", telephone=" + telephone + ", adresse="
                + adresse + ", dateInscription=" + dateInscription + ", actif=" + actif + ", typeUtilisateur="
                + typeUtilisateur + ", produits=" + produits + "]";
    }
}
